name: 'regex-lint-gh-action'
description: 'An easy-to-configure static regex lint github action.'
author: 'Candid Health'
inputs:
  file:
    required: true
    description: 'The file-path of the configuration file. See the repo README for configuration options.'
    default: '.github/regex-lint.yml'
runs:
  using: 'node16'
  main: 'dist/index.js'
